# Generated by Django 5.1.1 on 2024-09-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование сети')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Аптечные сети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование препарата')),
                ('corp', models.CharField(max_length=50, verbose_name='Производитель')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('drug_form', models.CharField(max_length=50, verbose_name='Форма выпуска')),
                ('drug_type', models.CharField(max_length=50, verbose_name='Форма отпуска')),
                ('price', models.IntegerField(verbose_name='Цена товара, сом')),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование аптеки')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('pharm_chain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharm.pharmchain')),
            ],
            options={
                'verbose_name_plural': 'Аптеки',
                'ordering': (['city'], ['name']),
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя менеджера')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия менеджера')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('pharm_chain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharm.pharmchain')),
            ],
            options={
                'verbose_name_plural': 'Менеджеры',
                'ordering': (['surname'], ['chain']),
            },
        ),
    ]
