# Generated by Django 5.1.1 on 2024-09-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0002_brand_city_country_drugform_drugtype_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name'], 'verbose_name_plural': 'Бренды>'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': (['country'], ['city_name']), 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='corporation',
            options={'ordering': (['corp_name'], ['corp_country']), 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['counry_name'], 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['drug_name'], 'verbose_name_plural': 'Лекарственные средства'},
        ),
        migrations.AlterModelOptions(
            name='drugform',
            options={'ordering': ['form_name'], 'verbose_name_plural': 'Лекарственные формы'},
        ),
        migrations.AlterModelOptions(
            name='drugtype',
            options={'ordering': ['drug_type'], 'verbose_name_plural': 'Формы отпуска'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['drug'], 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name_status'], 'verbose_name_plural': 'Статусы'},
        ),
    ]
