# Generated by Django 5.1.1 on 2024-09-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0003_alter_brand_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city_name'], 'verbose_name_plural': 'Города'},
        ),
    ]
