# Generated by Django 5.1.1 on 2024-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0005_drugstatus_workstatus_alter_drug_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=25, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name_plural': 'Статусы заказа',
                'ordering': ['order_status'],
            },
        ),
        migrations.AlterField(
            model_name='workstatus',
            name='work_status',
            field=models.CharField(max_length=25, verbose_name='Статус работы аптеки'),
        ),
    ]
