# Generated by Django 5.1.1 on 2024-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0006_orderstatus_alter_workstatus_work_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporation',
            options={'ordering': ['corp_name'], 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ['name'], 'verbose_name_plural': 'Аптеки'},
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
