# Generated by Django 5.1.1 on 2024-09-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0008_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='longitude',
        ),
    ]
