# Generated by Django 5.1.1 on 2024-10-14 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0010_alter_drug_options_rename_drug_name_drug_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharm.drug')),
            ],
            options={
                'verbose_name_plural': 'Приходы',
                'ordering': ['entry_date'],
            },
        ),
    ]
