# Generated by Django 5.1.1 on 2024-10-17 11:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0011_productentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 10, 17)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена товара, сом')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('amount', models.IntegerField(verbose_name='Cумма')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharm.drug')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharm.orderstatus')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharm.pharmacy')),
            ],
        ),
    ]
