# Generated by Django 5.1.1 on 2024-10-21 04:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0012_alter_productentry_entry_date_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_create'], 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.TextField(default='', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_create',
            field=models.DateField(default=datetime.date(2024, 10, 21)),
        ),
        migrations.AddField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default=datetime.date(2024, 10, 21)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pharm.orderstatus'),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 10, 21)),
        ),
    ]
